IBM/py-to-proto

jtd_to_proto/descriptor_to_message_class.py, tests/test_descriptor_to_message_class.py, tests/test_jtd_to_proto.py
Closes #7 
This PR adds support for top-level JTD enum schemas and converting them to `EnumTypeWrapper` to match the behavior of compiled protobuf python modules.
=> Top level enums

jtd_to_proto/jtd_to_proto.py, tests/test_jtd_to_proto.py
Closes #18 
This PR mimics #4 and adds support for using in-memory references to `EnumDescriptor`s to reference pre-existing enums. With the addition of enums, the recursive interactions for the "fields" and "type" sections of `_jtd_to_proto_impl` got a little more complex. Previously, for imported types, only the name was returned and it was assumed to be `TYPE_MESSAGE`. Now, it needs to distinguish between `TYPE_MESSAGE` and `TYPE_ENUM`, so the return from the "type" section is a tuple of the `(str, int)` for the `(name, type)`.
=> Enum refs 18

jtd_to_proto/json_to_service.py, tests/test_json_to_service.py
Fix output descriptor type of generated client stub and update the e2e test to check for a different output type
Affects registration function on servicer, etc. as well
=> :bug: Fix client stub output descriptor

jtd_to_proto/jtd_to_proto.py, tests/test_jtd_to_proto.py
There are some problems in the way that we check our messages when registering things into the descriptor pool. This PR addresses them by building and comparing `FileDescriptorProto` objects for the potential conflict. More details provided in summary of changes!
The serialized content for the same proto objects is not always consistent. Depending on how things are created & where they are validated things like `type_name` may not be fully qualified, and for some (mysterious) reason, there are false collision errors when nested types are used.
A simple repro case for the latter is outlined below:
Happy - no nested messages
```python3
from jtd_to_proto import jtd_to_proto
msg_name = "Foo"
package = "foo.bar"
schema = {"properties": {"foo": {"type": "boolean"}}} …
```
=> Fix message collision check

jtd_to_proto/descriptor_to_file.py, jtd_to_proto/descriptor_to_message_class.py, jtd_to_proto/json_to_service.py, jtd_to_proto/jtd_to_proto.py, tests/test_descriptor_to_file.py, tests/test_json_to_service.py
Changes in PR address [Add .to_proto_file support for Services](https://github.com/IBM/jtd-to-proto/issues/30):
- extends `descriptor_to_file` to include ServiceDescriptor support
- updates to `service_descriptor_to_service` to enable write_proto and to_proto
- new method `_add_protobuf_serializers` to reduce redundancy
Concerns:
- we're importing a private method `_add_protobuf_serializers` to `json_to_service.py` and want to consider whether this should be a public method instead.
=> Add .to_proto_file support for Services

.gitignore, jtd_to_proto/json_to_service.py, jtd_to_proto/jtd_to_proto.py, requirements.txt, tests/test_descriptor_to_file.py, tests/test_json_to_service.py, tests/test_jtd_to_proto.py
This PR removes the `jtd` validation due to a polluted GPLv3 license from `jtd`'s transitive dependency on `strict_rfc3339`
=> Remove validation

jtd_to_proto/json_to_service.py, jtd_to_proto/jtd_to_proto.py, jtd_to_proto/validation.py, tests/test_jtd_to_proto.py, tests/test_validation.py
This PR adds a local implementation of two `jtd` validation functions:
* `validation.is_valid_jtd`: This will check a given schema dict to ensure that it represents a valid `JTD` schema
* `validation.validat_jtd`: This will check a given object against a given schema
These validation steps replace the validation from the `jtd` package and finish removing the dependency
=> Internal validation

jtd_to_proto/json_to_service.py, jtd_to_proto/jtd_to_proto.py, tests/test_json_to_service.py
Fixes a bug where a duplicate json_to_service invocation would fail if protobuf was installed with binaries.
(No idea why it worked in the pure python protobuf impl in the first place, but... /shrug)
=> :bug: fix duplicate service def bug

jtd_to_proto/validation.py, tests/test_validation.py
This PR fixes the validation functions so that types can reference pre-existing protobuf descriptors
=> ValidateDescriptors: Add support for protobuf descriptors as types

.github/workflows/tests.yml, jtd_to_proto/descriptor_to_message_class.py
This PR adds to #39 to support protobuf 3.20 where `Descriptor._concrete_class` didn't exist at all
=> Fix backwards compat

.gitignore, jtd_to_proto/jtd_to_proto.py, tests/test_json_to_service.py, tests/test_jtd_to_proto.py
Closes https://github.com/IBM/jtd-to-proto/issues/34
This PR extends the functionality that implements the field descriptors for `optionalProperties` inside messages.
For these optional properties, a `oneof` is added which contains a single field which is the field descriptor for that optional property 🤯 
This mimics how `protoc` creates message descriptors, if you inspect one compiled with an optional field you'll see a oneof with a single field inside it.
=> Support `optionalProperties`

jtd_to_proto/descriptor_to_file.py, jtd_to_proto/jtd_to_proto.py, tests/test_descriptor_to_file.py, tests/test_jtd_to_proto.py
Closes https://github.com/IBM/jtd-to-proto/issues/43
Also fixes a bug where putting a list in `optionalProperties` would break
This PR adds special handling in the `descriptor_to_file` function to detect internal oneofs that were added to support optional fields. (These oneofs only have a single field in them, and all start with `_`)
This ensures that both:
- These internal oneofs are not explicitly rendered to protobuf, and
- The fields in these oneofs are explictly rendered, with the `optional` keyword in front
=> Render optional fields

jtd_to_proto/converter_base.py, jtd_to_proto/json_to_service.py, jtd_to_proto/jtd_to_proto.py, jtd_to_proto/utils.py, tests/test_jtd_to_proto.py
This PR hoists the core logic out of `jtd_to_proto` into the `ConverterBase` base class and provides hooks where the JTD-specific logic lives. It then reimplements `jtd_to_proto` to be a wrapper around a `JtdConverter` instance.
It's become clear that the logic here is not limited to converting inbound JTD schemas. In an effort to expand the types of input schemas that can be converted into proto descriptors, we want to keep the skeleton of the `jtd_to_proto` logic while lifting out all of the `jtd`-specific logic. The next target converter will take `dataclass`es and `Enum`s as input to provide a seamless pythonic schema type for creating proto descriptors.
=> Schema to proto abstraction

Dockerfile
The point of release test is to make sure the tests still pass
=> FixReleaseTestForNewVersions: Don't run coverage in release test

py_to_proto/dataclass_to_proto.py, tests/test_dataclass_to_proto.py
This PR fixes support for `Optional[X]` fields:
```py
@dataclass
class Foo:
foo: Optional[int]
dataclass_to_proto("foo.bar", Foo)
```
The fix is robust to various combinations of wrapping between `Annotated`, `Optional`, and `Union`.
=> Optional not oneof

py_to_proto/utils.py, tests/test_json_to_service.py
Addendum to #51 where client and server streaming support was added through `json_to_service`. These lines are now testable.
=> :white_check_mark: Add duplicate client and server streaming tests

py_to_proto/dataclass_to_proto.py, tests/test_dataclass_to_proto.py
Add underscore between `oneof` name and the `type name` for a much better naming experience!
=> 🎨 add underscore to oneof field names

py_to_proto/dataclass_to_proto.py, tests/test_dataclass_to_proto.py
If we now have a `Dataclass` like this:
```
@dataclass
class Baz:
baz: Union[List[str], List[int]]
```
It takes each `List[x]` type and wraps that in a `sub-message` with a single repeated `x` field, then use that `sub-type` in the parent `oneof`
The corresponding `proto` file looks like this:
```
/*------------------------------------------------------------------------------
* AUTO GENERATED
*----------------------------------------------------------------------------*/
syntax = "proto3";
package foo.bar;
/*-- MESSAGES ----------------------------------------------------------------*/
message Baz {
/*-- nested messages --*/
message StrSequence {
/*-- fields --*/
repeated string values = 1;
}
message IntSequence {
/*-- fields --*/
repeated int64 values = 1;
}
/*-- fields --*/
/*-- oneofs …
```
=> ✨ add list support to union

py_to_proto/dataclass_to_proto.py, tests/test_dataclass_to_proto.py
This PR attempts to fix multiple unions of list issue. This PR makes it such that 
`baz: Union[List[str], List[int]]` gets converted to `BazIntSequence` and `BazStrSequence` (instead of `IntSequence` and `StrSequence`) so that there are no more name collisions if there are multiple unions within the same `dataclass`.
related to https://github.com/caikit/caikit/issues/277
=> 🐛 fix multiple union list bug

py_to_proto/descriptor_to_file.py, tests/test_descriptor_to_file.py
When serializing an in-memory `MethodDescriptor` to a `.proto` file, include `client_streaming` and `server_streaming` information.
NOTE: This is tricky because these fields are [held in the underlying C structure](https://github.com/protocolbuffers/upb/blob/main/upb/util/def_to_proto.c#L471), but are [not exposed in the in-memory python class](https://github.com/protocolbuffers/upb/blob/main/python/descriptor.c#L1334). To work around this, we serialize to the `descriptor_pb2.MethodDescriptor` object to pull the information.
=> ServiceStreamingDescriptor: Support streaming rpcs in descriptor_to_file

py_to_proto/converter_base.py, tests/test_dataclass_to_proto.py, tests/test_jtd_to_proto.py
Ideally, same name `proto` files with different package names should be allowed to coexist within the same descriptor pool. But the reason it doesn't work right now is while checking for `_are_same_file_descriptors`, we check if the package name for `proto` files is the same or not. If it's not, we error out saying the files have different content but have the same name.  
This PR ensures they can coexist by appending `package name` to the file descriptor name so that the 2 file descriptors are named different now for the same name but different package `proto` file
=> 🐛 append package name to file descriptors

Dockerfile
Essentially the `release_test` should happen after release to control the order
=> 🐛 fix order of docker stages
